// Re-export everything from supabaseChatService for backward compatibility
export {
  searchUserByUsername,
  searchUsersByUsernamePrefix,
  getUserById,
  sendFriendRequest,
  acceptFriendRequest,
  rejectFriendRequest,
  subscribeToPendingRequests,
  subscribeToFriends,
  getOrCreateDMChat,
  subscribeToChats,
  sendMessage,
  clearUnreadCount,
  clearChat,
  subscribeToMessages,
  createGroup,
  addGroupMember,
  removeGroupMember,
  subscribeToUserPresence,
  setTypingStatus,
  subscribeToTypingStatus,
  syncProfileToSupabase,
  setUserPresence,
} from './supabaseChatService';
